# config.yaml
jira:
  url: "URL"
  user: "TOKEN"
  token: "TOKEN"
  query: 'project = "PROJ" AND status = "In Progress"'

time:
  min: 3
  max: 4

telegram:
  token: "NONE"
  chat_id: "NONE"

gitlab:
  url: "https://gitlab.com/api/v4"
  token: "TOKEN"

chatgpt:
  token: "TOKEN"

database:
  path: "issues.db"

default_tasks:
  - "PROJ-123"
  - "PROJ-46"
